/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Excepciones.NoEtiquetaValida;
import Objetos.DeltaMatroide;
import Objetos.Generador;
import Objetos.GraperFactible;
import Objetos.SubMatriz;
import Recursos.ElementoFolder;
import Recursos.MiRender;
import Recursos.modeloArbol.CeldaModelo;
import Tested.Main;
import static Tested.Main.datos;
import static Tested.Main.deltaMatroides;
import java.awt.Color;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
/**
 *
 * @author Diego
 */
public class DeltaMatroidePropiedades extends javax.swing.JFrame {

    /**
     * Creates new form DeltaMatroidePropiedades
     */
    
    private DeltaMatroide matroide;
    private Highlighter hilit;
    private Highlighter.HighlightPainter painter;
    public  boolean[][] celdas;
   
    public DeltaMatroidePropiedades() {
        matroide=new DeltaMatroide(new LinkedList<LinkedList<Integer>>(), "", new String[1]);
       // matroide=e;
        initComponents();
        Main.cargaListaMatroides(listaMatroides);
      //  llenaDeFalsos();
        if(matroide.getM()!=null)llenaDeFalsos();
        iniciaComponentes();
        cargaMatroide();
   
       
    }
    public boolean[][] getCeldas() {
        return celdas;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaMatroides = new javax.swing.JTree();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFactibles = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        familiaGuardarButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        familiaText = new javax.swing.JTextField();
        familiaEditButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        etiquetasTable = new javax.swing.JTable();
        etiquetasEditarButton = new javax.swing.JButton();
        etiquetasGuardarButton = new javax.swing.JButton();
        cancelEditionButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoDelta::Propiedades del DeltaMatroide ");
        setIconImage(Main.getIconImage());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("<html><p>Aqui puedes editar los atributos del Delta-Matroide como las etiquetas o el nombre de la Familia,</p><p> tambien puedes ver los factibles y sus SubMatrices Asociadas (si es que existe)</p></html>");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jButton1.setText("Regresar a Menu");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        listaMatroides.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroidesTreeCollapsed(evt);
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroidesTreeExpanded(evt);
            }
        });
        listaMatroides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMatroidesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaMatroides);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/property_time50.png"))); // NOI18N

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        listaFactibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFactiblesMouseClicked(evt);
            }
        });
        listaFactibles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listaFactiblesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(listaFactibles);

        jLabel5.setText("Factibles:");

        jLabel6.setText("Sub-Matriz Asociada");

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabla2);

        jButton3.setText("Ordenar SubConjuntos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.setText("Matriz Asociada");

        familiaGuardarButton.setText("Guardar");
        familiaGuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiaGuardarButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Delta-Matroide en el Campo:");

        familiaText.setEditable(false);

        familiaEditButton.setText("Editar");
        familiaEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiaEditButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de Familia:");

        jLabel2.setText("Conjunto V=");

        etiquetasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Etiquetas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(etiquetasTable);

        etiquetasEditarButton.setText("Editar");
        etiquetasEditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetasEditarButtonActionPerformed(evt);
            }
        });

        etiquetasGuardarButton.setText("Guardar");
        etiquetasGuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetasGuardarButtonActionPerformed(evt);
            }
        });

        cancelEditionButton.setText("Cancelar");
        cancelEditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cancelEditionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetasGuardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetasEditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(familiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(familiaEditButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(familiaGuardarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(familiaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(familiaEditButton)
                        .addComponent(familiaGuardarButton)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(etiquetasEditarButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiquetasGuardarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelEditionButton)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(13, 13, 13)))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Importar área de trabajo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exportar área de trabajo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem3.setText("Cerrar ProyectoDelta sin guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ir a");

        jMenuItem4.setText("DeltaMatroides desde matrices");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Validar DeltaMatroide");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Evaluar Isomorfismo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator4);

        jMenuItem7.setText("Calcular Menores");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Clases de Delta-Equivalencia");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);
        jMenu2.add(jSeparator3);

        jMenuItem9.setText("Asistente Para listas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem10.setText("Manual de usuario");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Acerca de ...");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void etiquetasEditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetasEditarButtonActionPerformed
        // TODO add your handling code here:
        
          String datos[][]=new String[matroide.getEtiquetas().length][2];
        String col[]={"Antes","Despues"};
        for(int i=0;i<matroide.getEtiquetas().length;i++){
            datos[i][0]=matroide.getEtiquetas()[i];
            datos[i][1]="";
        }
        activaDesactivaTabla(datos,col,true);
        cancelEditionButton.setVisible(true);
        etiquetasGuardarButton.setVisible(true);
    }//GEN-LAST:event_etiquetasEditarButtonActionPerformed
    boolean editar=true;
    private void familiaEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiaEditButtonActionPerformed
        // TODO add your handling code here:
        if(editar){
            familiaText.setEditable(true);
            familiaEditButton.setText("Guardar");
            editar=!editar;
        }else{
            matroide.setNombreFam(familiaText.getText());
            familiaGuardarButton.setVisible(false);
            familiaText.setEditable(false);
            cargaMatroide();
            familiaEditButton.setText("Editar");
             editar=!editar;
            
        }
    }//GEN-LAST:event_familiaEditButtonActionPerformed

    private void familiaGuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiaGuardarButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_familiaGuardarButtonActionPerformed
    LinkedList<Integer> listaEnteros;
    private void listaFactiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFactiblesMouseClicked
         // TODO add your handling code here:
         
        int index= listaFactibles.getSelectedIndex();
        if(index>=0 && matroide.getM()!=null){
            llenaDeFalsos();
           // determinanteLabel.setVisible(true);
//            String cad="Determinante :";
//            int det=matroide.getDeltas().get(index-1).getDeterminante();
//            cad+=""+det;
          //  determinanteLabel.setText(cad);
            
            GraperFactible aux=listaFactibles.getSelectedValue();
           // byte[][] matFat=(new Generador()).generarMatriz(auxiliar, M)
          
            //subMatrizText.setText(generaMatrisString(matFat.getMatriz(),false));
            if(aux.getFactible().size()!=0) {
                cargaSubMatrizEnTabla(aux);
            
            jScrollPane4.setVisible(true);
            }else {
                jScrollPane4.setVisible(false);
                llenaDeFalsos();
            jScrollPane4.setVisible(false);
            cargaMatriz();
            // determinanteLabel.setVisible(false);
            }
            
            
        }
                
    }//GEN-LAST:event_listaFactiblesMouseClicked

    private void etiquetasGuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetasGuardarButtonActionPerformed
        try {
            // TODO add your handling code here:
            
            String [] etiq=new String[etiquetasTable.getModel().getRowCount()];
            
            for (int i = 0; i < etiq.length; i++) {
                etiq[i]=(String) etiquetasTable.getModel().getValueAt(i, 1);
              //  System.out.println(etiq[i]);
            }
            if(validaEtiquetas(etiq)) matroide.setEtiquetas(etiq);
            cargaMatroide();
            cancelEditionButton.setVisible(false);
            etiquetasGuardarButton.setVisible(false);
        } catch (NoEtiquetaValida ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
  "Etiqueta invalida", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_etiquetasGuardarButtonActionPerformed

    private void cancelEditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditionButtonActionPerformed
        // TODO add your handling code here:
        cargaMatroide();
        cancelEditionButton.setVisible(false);
       etiquetasGuardarButton.setVisible(false);
    }//GEN-LAST:event_cancelEditionButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.ventanaMenu=new Menu2();
        Main.ventanaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        matroide.ordenaFamilia();
        cargaMatroide();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void listaFactiblesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaFactiblesKeyReleased
        // TODO add your handling code here:
           
        int index= listaFactibles.getSelectedIndex();
        if(index>=0 && matroide.getM()!=null){
            llenaDeFalsos();
           // determinanteLabel.setVisible(true);
//            String cad="Determinante :";
//            int det=matroide.getDeltas().get(index-1).getDeterminante();
//            cad+=""+det;
          //  determinanteLabel.setText(cad);
            
            GraperFactible aux=listaFactibles.getSelectedValue();
           // byte[][] matFat=(new Generador()).generarMatriz(auxiliar, M)
          
            //subMatrizText.setText(generaMatrisString(matFat.getMatriz(),false));
            if(aux.getFactible().size()!=0) {
                cargaSubMatrizEnTabla(aux);
            
            jScrollPane4.setVisible(true);
            }else {
                jScrollPane4.setVisible(false);
                llenaDeFalsos();
            jScrollPane4.setVisible(false);
            cargaMatriz();
            // determinanteLabel.setVisible(false);
            }
            
            
        }
    }//GEN-LAST:event_listaFactiblesKeyReleased

    private void listaMatroidesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMatroidesMouseClicked
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) listaMatroides.getLastSelectedPathComponent();
        if (nodoSelec != null) {
            try {

                
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
                
                if (aux.isIsFolder()) {
                    jPanel2.setVisible(false);
                   
                } else {
                    //System.out.println("entre falso");

                    this.matroide = aux.getMatrode();
                    if(matroide.getM()!=null)llenaDeFalsos();
                    //DefaultMutableTreeNode ok=new DefaultMutableTreeNode
                    iniciaComponentes();
                    
                    cargaMatroide();
                    jPanel2.setVisible(true);
                }
               
            } catch (java.lang.ClassCastException ex) {
                System.out.println("se selecciono raiz" + ex.getLocalizedMessage());
               
            }
        }
    }//GEN-LAST:event_listaMatroidesMouseClicked

    private void listaMatroidesTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroidesTreeCollapsed
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=false;

            } catch (java.lang.ClassCastException ex) {
                System.out.println("se selecciono raiz" + ex.getLocalizedMessage());
              
            }
        }
    }//GEN-LAST:event_listaMatroidesTreeCollapsed

    private void listaMatroidesTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroidesTreeExpanded
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=true;

            } catch (java.lang.ClassCastException ex) {
                System.out.println("se selecciono raiz" + ex.getLocalizedMessage());
              
            }
        }
    }//GEN-LAST:event_listaMatroidesTreeExpanded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Main.menubarImportar(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Main.menubarExportar(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Main.ventanaGenera=new GeneradorDeltaMatroide();
        Main.ventanaGenera.setVisible(true);
        this.setVisible(false);    
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Main.ventanaValidacion=new DeterminaDeltaMatroide();
        Main.ventanaValidacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Main.ventanaIsomorfismo=new Isomorfismo();
         Main.ventanaIsomorfismo.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Main.ventanaMenores=new Menores(null);
        Main.ventanaMenores.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Main.ventanaEquivalencias=new GeneradorClaseEquivalencia();
         Main.ventanaEquivalencias.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Main.ventanaListas=new ListasDeltaMatroides();
        Main.ventanaListas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    public String generaMatrisString(byte [][] mat, boolean modoEtiquetas){
        String cadena="";
        if(!modoEtiquetas){

            cadena+="   ";
            String aux[]=this.matroide.getEtiquetas();
            for(int i =0;i<mat.length;i++) cadena+=aux[listaEnteros.get(i)]+"   ";
            cadena+="\n";
            
            for(int i =0;i<mat.length;i++){
               cadena+=aux[listaEnteros.get(i)]+"  ";
               for(int j =0 ;j<mat.length;j++){
                   cadena+=mat[i][j];
                   if(j!=mat.length-1) cadena+="  ";
                }
               cadena+="\n";
            }
        }
        else{
            cadena+="     ";
            String aux[]=this.matroide.getEtiquetas();
            for(int i =0;i<mat.length;i++){ cadena+=aux[i];
                if(aux[i].length()==1) cadena+="   ";
                else cadena+="  ";
            }
            cadena+="\n";
            
            for(int i =0;i<mat.length;i++){
               cadena+=aux[i];
               if(aux[i].length()==1) cadena+="   ";
                else cadena+="  "; 
               for(int j =0 ;j<mat.length;j++){
                   cadena+=mat[i][j];
                   if(j!=mat.length-1) {
                       if(aux[i].length()==1) cadena+="   ";
                        else cadena+="  ";
                   }
                }
               cadena+="\n";
             }
            
            
        }
        return cadena;
        
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelEditionButton;
    private javax.swing.JButton etiquetasEditarButton;
    private javax.swing.JButton etiquetasGuardarButton;
    private javax.swing.JTable etiquetasTable;
    private javax.swing.JButton familiaEditButton;
    private javax.swing.JButton familiaGuardarButton;
    private javax.swing.JTextField familiaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<GraperFactible> listaFactibles;
    private javax.swing.JTree listaMatroides;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables

    private void cargaMatroide() {
        
        familiaText.setText(matroide.getNombreFam());
       
         String datos[][]=new String[matroide.getEtiquetas().length][1];
        String col[]={"Etiquetas"};
        for(int i=0;i<matroide.getEtiquetas().length;i++)
            datos[i][0]=matroide.getEtiquetas()[i];
        
        activaDesactivaTabla(datos,col,false);
        
        String ab="{";
       
        for(int i=0;i<matroide.getEtiquetas().length;i++){
           
            datos[i][0]=matroide.getEtiquetas()[i];
            ab+=matroide.getEtiquetas()[i];
            if(i==matroide.getEtiquetas().length-1) ;
            else ab+=",";
        }
        ab+="}";
        jLabel3.setText(ab);
        jLabel7.setText(matroide.toString());
        
        jLabel8.setText("Huella:  "+matroide.getHuella());
        cargaFactibles();
        cargaMatriz();
       this.setTitle("ProyectoDelta::Propiedades del DeltaMatroide "+this.matroide.getNombreFam());
        
        
    }
    @Override
        public void dispose() {

        if(JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas cerrar ProyectoDelta?", "¿Esta seguro?", JOptionPane.YES_NO_OPTION)==0){
            Main.fin = false;
            //datos.setFlags(flags);
            datos.setNuevoAFalso();
            datos.setMatroides(deltaMatroides);
            Main.flujo.SerializaDatos(datos);
            super.dispose();
            System.exit(0);
        }

    }

    private void cargaFactibles() {
        DefaultListModel<GraperFactible> model = new DefaultListModel<>();
    
       for(int i=0;i<matroide.getFamilia().size();i++){
           model.addElement(new GraperFactible(matroide.getFamilia().get(i),i,matroide.getEtiquetas()));
       }
       listaFactibles.setModel(model);
      
    }

    private void cargaMatriz() {
        
        if(matroide.getM()!=null){
          cargaMatrizEnTabla(matroide.getM());
         
            tabla2.setVisible(false);
            String []a={""};
            String datos[][]={{""}};
            DefaultTableModel e = new DefaultTableModel(datos,a);
        
            tabla2.setModel(e);
        }else {
            tabla.setVisible(false);
            tabla2.setVisible(false);
            String []a={""};
            String datos[][]={{""}};
            DefaultTableModel e = new DefaultTableModel(datos,a);
            tabla.setModel(e);
            tabla2.setModel(e);
            
        } // matrizText.setText("Sin Matriz");
        
//        hilit = new DefaultHighlighter();
//            painter = new DefaultHighlighter.DefaultHighlightPainter(Color.CYAN);
//            matrizText.setHighlighter(hilit);
//        try {
//            int salto=3+2*(matroide.getM()).length;
//            hilit.addHighlight(0, salto, painter);
//            int index=0;
//            String textMatris=matrizText.getText();
//            for (int i = 1; i <= matroide.getM().length; i++) {
//                int subIndx=textMatris.indexOf("\n", index);
//                System.out.println(subIndx);
//                hilit.addHighlight(subIndx, subIndx+1, painter);
//                index=subIndx+1;
//                
//            }
//            
//        } catch (BadLocationException ex) {
//            Logger.getLogger(DeltaMatroidePropiedades.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println("error");
//        }
        
        
    }

    private void activaDesactivaTabla(String datos[][],String []col,boolean b) {
        
        
      DefaultTableModel model=new DefaultTableModel(datos,col){
        public boolean isCellEditable(int rowIndex, int vColIndex) {
            return b;
        }}; //return false: Desabilitar edición de celdas.
        etiquetasTable.setModel(model);
    }

    private boolean validaEtiquetas(String[] etiq) throws NoEtiquetaValida {
        
        for (int i = 0; i < etiq.length; i++) {
           if(etiq[i].length()>2) throw new NoEtiquetaValida("la Etiqueta: "+etiq[i] +" no es Valida. Solo dos Caracteres como Maximo por Etiqueta") ;
            
        }
        
        
        
       return true;
    }

    private void iniciaComponentes() {
        
    // determinanteLabel.setVisible(false);
        familiaGuardarButton.setVisible(false);
       cancelEditionButton.setVisible(false);
       etiquetasGuardarButton.setVisible(false);
       jPanel2.setVisible(false);
    }
    private void cargaSubMatrizEnTabla(GraperFactible g){
       byte [][] m=(new Generador()).generarMatriz(g.getFactible(),matroide.getM());
        String Columnas[]=new String [m.length +1];
        Columnas[0]="";
        for (int i = 1; i < Columnas.length; i++) {
            Columnas[i]=matroide.getEtiquetas()[g.getFactible().get(i-1)];
            
        }
        
        String datos[][]=new String[m.length][m.length+1];
        LinkedList<Integer> aux1=g.getFactible();
        LinkedList<Integer> aux2=g.getFactible();
        for (int i = 0; i < m.length; i++) {
            datos[i][0]=matroide.getEtiquetas()[g.getFactible().get(i)];
            for (int j = 1; j <=m.length; j++) {
                datos[i][j]=m[i][j-1]+"";
                celdas[aux1.get(i)][1+aux1.get(j-1)]=true;
              //  System.out.println(celdas[aux1.get(i)][1+aux1.get(j-1)]);
            }
        }
        cargaMatriz();
        DefaultTableModel tm = new DefaultTableModel(datos, Columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                    if (0 == column)
                            return false;
                    return super.isCellEditable(row, column);
            }
        };
        tabla2 = new JTableImpl(tm);
      tabla2.getColumnModel().getColumn(0).setCellRenderer(tabla.getTableHeader().getDefaultRenderer());
      tabla2.setVisible(true);
      jScrollPane4.setViewportView(tabla2);
      
      
        
      
    }
    
    
    private void cargaMatrizEnTabla(byte[][] m) {
        String Columnas[]=new String [m.length+1];
        Columnas[0]="";
        for (int i = 1; i < Columnas.length; i++) {
            Columnas[i]=matroide.getEtiquetas()[i-1];
            
        }
       
        String datos[][]=new String[m.length][m.length+1];
        
        for (int i = 0; i < m.length; i++) {
            datos[i][0]=matroide.getEtiquetas()[i];
            for (int j = 1; j <=m.length; j++) {
                datos[i][j]=m[i][j-1]+"";
                
            }
        }
        DefaultTableModel tm = new DefaultTableModel(datos, Columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                    if (0 == column)
                            return false;
                    return super.isCellEditable(row, column);
            }
        };
        tabla = new JTableImpl(tm);
        tabla.setDefaultRenderer (Object.class, new MiRender());
      tabla.getColumnModel().getColumn(0).setCellRenderer(tabla.getTableHeader().getDefaultRenderer());
      tabla.setVisible(true);
      jScrollPane5.setViewportView(tabla);
        
    }

    private void llenaDeFalsos() {
        celdas=new boolean[matroide.getM().length][matroide.getM().length+1];
        for (int i = 0; i < celdas.length; i++) {
            for (int j = 0; j < celdas.length+1; j++) {
                celdas[i][j]=false;
                
            }
            
        }
    }

    private class JTableImpl extends JTable {

        public JTableImpl(TableModel dm) {
            super(dm);
        }

        @Override
        public void changeSelection(int rowIndex, int columnIndex,
                boolean toggle, boolean extend) {
            if (columnIndex == 0)
                // Podemos llamar a changeSelecion() incrementando la columna en 1
                // o bien podríamos hacer directamente un return.
                super.changeSelection(rowIndex, columnIndex + 1, toggle, extend);
            else
                super.changeSelection(rowIndex, columnIndex, toggle, extend);
        }
    }
}
