/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Objetos.DeltaMatroide;
import Objetos.Huella;
import Recursos.ElementoFolder;
import Recursos.conjuntos.OperConj;
import Recursos.modeloArbol.CeldaModelo;
import Tested.Main;
import static Tested.Main.datos;
import static Tested.Main.deltaMatroides;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author diego
 */
public class Menores extends javax.swing.JFrame {

    /**
     * Creates new form Menores
     */
    private DeltaMatroide matroide;
    private LinkedList<DeltaMatroide> menoresBorrado,menoresContraccion;
    private OperConj operaciones;
    private int desface;
    private Huella hBorrado,hContraccion;
    boolean ultimoModo;
    
    public Menores(DeltaMatroide m) {
       operaciones=new OperConj();
      menoresBorrado=new LinkedList();
      menoresContraccion=new LinkedList();
       
       matroide=m;
       initComponents();
        buttonGroup1.add(jRadioButton1);
       buttonGroup1.add(jRadioButton2);
       buttonGroup1.add(jRadioButton3);
       jRadioButton2.setSelected(true);
       setLocationRelativeTo(null);
       Main.cargaListaMatroides(listaMatroides);
       if(matroide!=null) cargaMatroide();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMatroides = new javax.swing.JTree();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoDelta::Menores");
        setBackground(new java.awt.Color(102, 153, 255));
        setIconImage(Main.getIconImage());

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel1.setText("Conjunto [V]");

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N

        jLabel4.setText("X=");

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {""}));
        jSpinner1.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel5.setText("Resultados:");

        jButton1.setText("Calcular Menor");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jCheckBox1.setText("Ajustar el texto");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel6.setText("Borrado:");
        jLabel6.setEnabled(false);

        jLabel7.setText("Contraccion");
        jLabel7.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        listaMatroides.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroidesTreeCollapsed(evt);
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroidesTreeExpanded(evt);
            }
        });
        listaMatroides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMatroidesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaMatroides);

        jRadioButton1.setText("Factibles en serie");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Factibles por Cardinalidad");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Factibles por Lineas");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton3.setText("Calcular Todos");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menor50.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel9.setText("Elije un DeltaMatroide e introduce un elemento x para calcular un DeltaMatroide menor ");

        jButton4.setText("Guardar Resultados");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jButton5.setText("Regresar A Menú");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Importar área de trabajo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Exportar área de trabajo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Cerrar ProyectoDelta sin guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ir a");

        jMenuItem4.setText("DeltaMatroides desde matrices");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Validar DeltaMatroide");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Evaluar Isomorfismo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator3);

        jMenuItem7.setText("Clases de Delta-Equivalencia");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator4);

        jMenuItem8.setText("Propiedades de DeltaMatroides");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Asistente de listas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(270, 270, 270)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton3)
                                                    .addComponent(jRadioButton2)
                                                    .addComponent(jRadioButton1)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jScrollPane3)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton3))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jCheckBox1)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton3))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jCheckBox1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:nni
        jButton4.setEnabled(true);
        jTextArea1.setText("");
        jTextArea2.setText("");
        ejecutaOperaciones(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        ultimoModo=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setLineWrap(jCheckBox1.isSelected());
        jTextArea2.setLineWrap(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void listaMatroidesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMatroidesMouseClicked
        // TODO add your handling code here:
          
         DefaultMutableTreeNode nodoSelec=  (DefaultMutableTreeNode)listaMatroides.getLastSelectedPathComponent();
         if(nodoSelec!=null){
              jButton4.setEnabled(false);
            try{
                ElementoFolder aux= (ElementoFolder) nodoSelec.getUserObject();
                //si es un folder
              if(aux.isIsFolder()) {
                  //System.out.println("entre verdadero");
                 
            }else
              {
                  //System.out.println("entre falso");     
                this.matroide=aux.getMatrode();
                  //DefaultMutableTreeNode ok=new DefaultMutableTreeNode
                cargaMatroide();
                jButton4.setEnabled(false);
              }
              
              
             } catch(java.lang.ClassCastException  ex){
              
             }
     }
    }//GEN-LAST:event_listaMatroidesMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea2.setText("");
        for(int i=0;i<menoresBorrado.size();i++){
            menoresBorrado.get(i).setModeFactibles0();
            menoresContraccion.get(i).setModeFactibles0();
        }
        despliegaResultados(ultimoModo);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
          jTextArea1.setText("");
        jTextArea2.setText("");
        for(int i=0;i<menoresBorrado.size();i++){
            menoresBorrado.get(i).setModeFactibles1();
            menoresContraccion.get(i).setModeFactibles1();
        }
        despliegaResultados(ultimoModo);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
          jTextArea1.setText("");
        jTextArea2.setText("");
        for(int i=0;i<menoresBorrado.size();i++){
            menoresBorrado.get(i).setModeFactibles2();
            menoresContraccion.get(i).setModeFactibles2();
        }
        despliegaResultados(ultimoModo);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          jButton4.setEnabled(true);
        jTextArea1.setText("");
        jTextArea2.setText("");
            RBorrado=new LinkedList();
            RContraccion=new LinkedList();
             ejecutaOperaciones(false);
             ultimoModo=false;
             jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
           
                
                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Main.ventanaSelector= new SelectorMatroide(this,true,5);
        Main.ventanaSelector.setVisible(true);
        ElementoFolder carpeta=(ElementoFolder)Main.pila.pop();
        if(JOptionPane.showConfirmDialog(null, "Se guardaran los "+(menoresContraccion.size()+menoresBorrado.size())+" Delta-Matroides en "
                + "la carpeta "+carpeta.getNombre()+" ¿Deseas Continuar?", "Reporte de Operaciones", JOptionPane.YES_NO_OPTION)==0){
            for(int i=0;i<menoresBorrado.size();i++){
                carpeta.folder.add(new ElementoFolder(false,menoresBorrado.get(i).getNombreFam(),menoresBorrado.get(i),carpeta));
                carpeta.folder.add(new ElementoFolder(false,menoresContraccion.get(i).getNombreFam(),menoresContraccion.get(i),carpeta));
            }
        }
        
        Main.cargaListaMatroides(listaMatroides);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void listaMatroidesTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroidesTreeCollapsed
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=false;

            } catch (java.lang.ClassCastException ex) {
                System.out.println("se selecciono raiz" + ex.getLocalizedMessage());
              
            }
        }
    }//GEN-LAST:event_listaMatroidesTreeCollapsed

    private void listaMatroidesTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroidesTreeExpanded
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=true;

            } catch (java.lang.ClassCastException ex) {
                System.out.println("se selecciono raiz" + ex.getLocalizedMessage());
              
            }
        }
    }//GEN-LAST:event_listaMatroidesTreeExpanded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Main.menubarImportar(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Main.menubarExportar(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
          Main.ventanaListas=new ListasDeltaMatroides();
        Main.ventanaListas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
          Main.ventanaGenera=new GeneradorDeltaMatroide();
        Main.ventanaGenera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
          Main.ventanaValidacion=new DeterminaDeltaMatroide()
                ;
        Main.ventanaValidacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
          Main.ventanaIsomorfismo=new Isomorfismo();
        Main.ventanaIsomorfismo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Main.ventanaEquivalencias=new GeneradorClaseEquivalencia();
        Main.ventanaEquivalencias.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         Main.ventanaPropiedades=new DeltaMatroidePropiedades();
        Main.ventanaPropiedades.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          Main.ventanaMenu=new Menu2();
        Main.ventanaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    @Override
      public void dispose() {

        if(JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas cerrar ProyectoDelta?", "¿Esta seguro?", JOptionPane.YES_NO_OPTION)==0){
            Main.fin = false;
            //datos.setFlags(flags);
            datos.setNuevoAFalso();
            datos.setMatroides(deltaMatroides);
            Main.flujo.SerializaDatos(datos);
            super.dispose();
            System.exit(0);
        }

    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree listaMatroides;
    // End of variables declaration//GEN-END:variables

    private void cargaMatroide() {
        
   //    this.matroide=(DeltaMatroide) Main.deltaMatroides.get(index); 
         jSpinner1.setEnabled(true);
              jButton1.setEnabled(true);
               jButton3.setEnabled(true);
       jRadioButton1.setEnabled(false);
       jRadioButton2.setEnabled(false);
       jRadioButton3.setEnabled(false);
       SpinnerListModel nm = new SpinnerListModel();
       LinkedList a=new LinkedList();
        for (int i = 0; i < matroide.getEtiquetas().length; i++) {
            
            a.add( matroide.getEtiquetas()[i]);
            
            
        }
        nm.setList(a);
       
       jSpinner1.setModel(nm);
      
         //listaMatroides.setSelectedIndex(index);

        int V=matroide.getEtiquetas().length;
               
        String conjuCad="V={";
        for(int i =0;i<V;i++){
            if(i<V-1) conjuCad+=matroide.getEtiquetas()[i]+",";
            else conjuCad+=matroide.getEtiquetas()[i]+"";
        }
         conjuCad+="}";
         jLabel2.setText(conjuCad);
         jLabel3.setText(matroide.getNombreFam()+"={"+matroide.getResultado()+"}");
     
              jSpinner1.setEnabled(true);
              jButton1.setEnabled(true);
    }
     
    LinkedList <LinkedList <Integer>> FBorrado=new LinkedList();
    LinkedList <LinkedList <Integer>> FContraccion=new LinkedList();
    
    LinkedList <LinkedList <LinkedList <Integer>>> RBorrado=new LinkedList();
    LinkedList <LinkedList <LinkedList <Integer>>> RContraccion=new LinkedList();
        
    private void ejecutaOperaciones(boolean modo) {
        LinkedList <LinkedList <Integer> > temp= matroide.getFamilia();
        jButton4.setEnabled(true);
         try{
        if(modo){ 
            
                Elemento=(String)jSpinner1.getValue();
               
                
                DeltaMatroide e= matroide.getMenorBorrado((String) jSpinner1.getValue()),
                              d= matroide.getMenorContraccion((String) jSpinner1.getValue());
                menoresBorrado.add(e);
                menoresContraccion.add(d);
               
                 
        }else{
            
             
              
            for (int i = 0; i < matroide.getEtiquetas().length; i++) {
                menoresBorrado.add(matroide.getMenorBorrado(matroide.getEtiquetas()[i]));
                menoresContraccion.add(matroide.getMenorContraccion(matroide.getEtiquetas()[i]));
            } 
        }
        despliegaResultados(modo);
         }catch(Exception e){
                    
                }
    }
    int algo;
     String Elemento;
    
    private void despliegaResultados(boolean modo){
        
        for (int i = 0; i < menoresBorrado.size(); i++) {
            llenaTexto(menoresBorrado.get(i),menoresContraccion.get(i));
        }
                
            

    }
    void llenaTexto(DeltaMatroide b,DeltaMatroide c){
          
              
              jTextArea1.append(b.getNombreFam()+"={"+b.getResultado()+"}\n");
              jTextArea1.append("Huella "+ b.getHuella() +"\n");
              jTextArea1.append("\n________________________________________________________\n");
              jTextArea1.append("\n________________________________________________________\n");
              
              
              jTextArea2.append(c.getNombreFam()+"={"+c.getResultado()+"}\n");
              jTextArea2.append("Huella "+ c.getHuella() +"\n");
              jTextArea2.append("\n________________________________________________________\n");
              jTextArea2.append("\n________________________________________________________\n");
              
    }

    private int obtenIndexEtiqueta(String value) {
       String [] ar=matroide.getEtiquetas();
        for (int i = 0; i < ar.length; i++) 
            if( ar[i].compareTo(value)==0) return i;
            
        return -1;
    }
}