/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Formas.*;
import Tested.*;
import static Tested.Main.datos;
import static Tested.Main.deltaMatroides;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.UIManager;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;






/**
 *
 * @author Thor
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      

        initComponents();
        setLocationRelativeTo(null);
    
    
    }

    public void dispose(){
        
        Main.fin=false;
        //datos.setFlags(flags);
        datos.setNuevoAFalso();
        datos.setMatroides(deltaMatroides);
        Main.flujo.SerializaDatos(datos); 
        super.dispose();
        System.exit(0); 

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        TwistingButton = new javax.swing.JButton();
        Matroide = new javax.swing.JButton();
        Menores = new javax.swing.JButton();
        Validacion = new javax.swing.JButton();
        Validacion1 = new javax.swing.JButton();
        Validacion2 = new javax.swing.JButton();
        Validacion3 = new javax.swing.JButton();
        Validacion4 = new javax.swing.JButton();
        Validacion5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienvenidos");
        setIconImage(Main.getIconImage());
        setMinimumSize(new java.awt.Dimension(766, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Utilerias:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 130, 240, 40);

        TwistingButton.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        TwistingButton.setForeground(new java.awt.Color(204, 255, 255));
        TwistingButton.setText("Twisting");
        TwistingButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TwistingButton.setContentAreaFilled(false);
        TwistingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwistingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TwistingButton);
        TwistingButton.setBounds(10, 320, 360, 40);

        Matroide.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Matroide.setForeground(new java.awt.Color(204, 255, 255));
        Matroide.setText("Generar DeltaMatroide");
        Matroide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Matroide.setContentAreaFilled(false);
        Matroide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatroideActionPerformed(evt);
            }
        });
        getContentPane().add(Matroide);
        Matroide.setBounds(10, 220, 360, 40);

        Menores.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Menores.setForeground(new java.awt.Color(204, 255, 255));
        Menores.setText("Calculo de Menores");
        Menores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menores.setContentAreaFilled(false);
        Menores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenoresActionPerformed(evt);
            }
        });
        getContentPane().add(Menores);
        Menores.setBounds(10, 270, 360, 40);

        Validacion.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Validacion.setForeground(new java.awt.Color(204, 255, 255));
        Validacion.setText("Generar Orientaciones");
        Validacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Validacion.setContentAreaFilled(false);
        Validacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidacionActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion);
        Validacion.setBounds(390, 220, 360, 40);

        Validacion1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Validacion1.setForeground(new java.awt.Color(204, 255, 255));
        Validacion1.setText("Analizar Familas de Subconjuntos");
        Validacion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Validacion1.setContentAreaFilled(false);
        Validacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Validacion1ActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion1);
        Validacion1.setBounds(10, 170, 360, 40);

        Validacion2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Validacion2.setForeground(new java.awt.Color(204, 255, 255));
        Validacion2.setText("Acerca de..");
        Validacion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Validacion2.setContentAreaFilled(false);
        Validacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Validacion2ActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion2);
        Validacion2.setBounds(660, 20, 90, 30);

        Validacion3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Validacion3.setForeground(new java.awt.Color(204, 255, 255));
        Validacion3.setText("Manual");
        Validacion3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Validacion3.setContentAreaFilled(false);
        Validacion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Validacion3ActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion3);
        Validacion3.setBounds(560, 20, 90, 30);

        Validacion4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Validacion4.setForeground(new java.awt.Color(204, 255, 255));
        Validacion4.setText("Propiedades de Delta-Matroides");
        Validacion4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Validacion4.setContentAreaFilled(false);
        Validacion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Validacion4ActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion4);
        Validacion4.setBounds(390, 170, 360, 40);

        Validacion5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Validacion5.setForeground(new java.awt.Color(204, 255, 255));
        Validacion5.setText("Isomorfismo");
        Validacion5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Validacion5.setContentAreaFilled(false);
        Validacion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Validacion5ActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion5);
        Validacion5.setBounds(390, 270, 360, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ProyectoDelta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(11, 30, 440, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Investigacion en Delta-Matroides");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 70, 510, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fano.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -50, 950, 550);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/polygon_3-wallpaper-960x600.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatroideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatroideActionPerformed
        // TODO add your handling code here:
        Main.ventanaGenera = new GeneradorDeltaMatroide();
        Main.ventanaGenera.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_MatroideActionPerformed

    private void MenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenoresActionPerformed
        // TODO add your handling code here:
         Main.ventanaMenores = new Menores(null);
        Main.ventanaMenores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenoresActionPerformed

    private void ValidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidacionActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_ValidacionActionPerformed

    private void TwistingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwistingButtonActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_TwistingButtonActionPerformed

    private void Validacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Validacion1ActionPerformed
        // TODO add your handling code here:
        Main.ventanaValidacion=new DeterminaDeltaMatroide();
        Main.ventanaValidacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Validacion1ActionPerformed

    private void Validacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Validacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Validacion2ActionPerformed

    private void Validacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Validacion3ActionPerformed
        // TODO add your handling code here:
        try {
            File path = new File ("manual.pdf");
            Desktop.getDesktop().open(path);
       }catch (IOException ex) {
            ex.printStackTrace();
       }
    }//GEN-LAST:event_Validacion3ActionPerformed

    private void Validacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Validacion4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Validacion4ActionPerformed

    private void Validacion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Validacion5ActionPerformed
        // TODO add your handling code here:
        Main.ventanaIsomorfismo=new Isomorfismo();
        Main.ventanaIsomorfismo.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_Validacion5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Matroide;
    private javax.swing.JButton Menores;
    private javax.swing.JButton TwistingButton;
    private javax.swing.JButton Validacion;
    private javax.swing.JButton Validacion1;
    private javax.swing.JButton Validacion2;
    private javax.swing.JButton Validacion3;
    private javax.swing.JButton Validacion4;
    private javax.swing.JButton Validacion5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
