/*
 * Copyright (C) 2017 diego
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Formas;

import Objetos.DeltaMatroide;
import Recursos.ConstructorFamilias;
import Recursos.ElementoFolder;
import Recursos.OperacionesListas;
import Tested.Main;
import static Tested.Main.datos;
import static Tested.Main.deltaMatroides;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author diego
 */
public class ListasDeltaMatroides extends javax.swing.JFrame {

    boolean salidaIsomorfismo = false;
    /**
     * Creates new form ListasDeltaMatroides
     */
    DefaultListModel<DeltaMatroide> modelo, modelo2;
    DefaultTableModel ModeloTablaA,ModeloTablaB,ModeloTablaR,TablaAdmi;
    ElementoFolder folder = Main.deltaMatroides;
    LinkedList<DeltaMatroide> A,B,resultado;
    ElementoFolder folderAdmin;
    int salida;

    public ListasDeltaMatroides() {
        initComponents();
        modelo = new DefaultListModel();
        modelo2 = new DefaultListModel();
        A=new LinkedList();
        B=new LinkedList();
        resultado=new LinkedList();
        ModeloTablaA=(DefaultTableModel) jTable1.getModel();
        ModeloTablaB=(DefaultTableModel) jTable2.getModel();
        ModeloTablaR=(DefaultTableModel) jTable3.getModel();
        TablaAdmi=(DefaultTableModel) jTable4.getModel();

      //  jList1.setModel(modelo);
        modelo2 = new DefaultListModel();
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
        jLabel11.setText(folder.getNombre());
        
        salida=-1;
        cargaBoton();

    }
public ListasDeltaMatroides(int pest,int salida) {
        initComponents();
        modelo = new DefaultListModel();
        modelo2 = new DefaultListModel();
        A=new LinkedList();
        B=new LinkedList();
        resultado=new LinkedList();
        ModeloTablaA=(DefaultTableModel) jTable1.getModel();
        ModeloTablaB=(DefaultTableModel) jTable2.getModel();
        ModeloTablaR=(DefaultTableModel) jTable3.getModel();
        TablaAdmi=(DefaultTableModel) jTable4.getModel();

      //  jList1.setModel(modelo);
        modelo2 = new DefaultListModel();
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
        jTabbedPane1.setSelectedIndex(pest);
        jLabel11.setText(folder.getNombre());
        this.salida=salida;
        cargaBoton();
    }
   private void cargaBoton(){
       
       switch(salida){
           case 0:
               jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delta.png"))); // NOI18N
               jButton15.setText("<html><body>Regresar a<br>Clases de Equivalencia</body></html>");
               
           break;
           
           case 1:
               jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/isomorfismo25.png"))); // NOI18N
               jButton15.setText("<html><body>Regresar a<br>Evaluar Isomorfismo</body></html>");
               
           break;
           
           default:
               jButton15.setVisible(false);
           break;
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaMatroides1 = new javax.swing.JTree();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaMatroides = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoDelta::Listas de DeltaMatroides");
        setIconImage(Main.getIconImage());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        listaMatroides1.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroides1TreeExpanded(evt);
            }
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroides1TreeCollapsed(evt);
            }
        });
        listaMatroides1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMatroides1MouseClicked(evt);
            }
        });
        listaMatroides1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                listaMatroides1ValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(listaMatroides1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "No", "Nombre", "Factibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setMinWidth(20);
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable4.getColumnModel().getColumn(0).setMaxWidth(20);
            jTable4.getColumnModel().getColumn(1).setMinWidth(40);
            jTable4.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable4.getColumnModel().getColumn(1).setMaxWidth(40);
            jTable4.getColumnModel().getColumn(2).setMinWidth(80);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable4.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Carpeta Seleccionada:");

        jButton8.setText("Mover Seleccionados");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Copiar Seleccionados");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Eliminar Seleccionados");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Agregar Nueva Carpeta");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N

        jButton12.setText("Borrar Carpeta");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Mover Carpeta");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel12.setText("Numero de Elementos contenidos:");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton12)
                                    .addComponent(jButton13))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Administrar", jPanel3);

        jLabel6.setText("Introduce la lista de los DeltaMatroides separados por un salto de linea en el formato indicado:");

        jLabel7.setText("nombre={{},{a,b},{c,d},{a,b,c}}");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Folder Seleccionado:");

        listaMatroides.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroidesTreeExpanded(evt);
            }
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                listaMatroidesTreeCollapsed(evt);
            }
        });
        listaMatroides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMatroidesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listaMatroides);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N

        jButton3.setText("Agregar Carpeta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3)))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Leer una lista", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Factibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Factibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(50);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(1).setMinWidth(100);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Factibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setEnabled(false);
        jScrollPane4.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(50);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable3.getColumnModel().getColumn(1).setMinWidth(100);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jLabel2.setText("Lista B");

        jLabel3.setText("Lista A");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Union", "Intersección", "A menos B", "B menos A", "Diferencia Simetrica" }));

        jButton1.setText("Comenzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Elegir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Elegir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Guardar Lista");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))))
        );

        jTabbedPane1.addTab("Operaciones", jPanel1);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lista50.png"))); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jButton14.setText("Regresar a Menú");
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/isomorfismo25.png"))); // NOI18N
        jButton15.setText("<html><body>Regresar a<br>Clases de Equivalencia</body></html>");
        jButton15.setOpaque(true);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Importar área de trabajo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exportar área de trabajo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Cerrar ProyectoDelta sin guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ir a");

        jMenuItem4.setText("DeltaMatroides desde matrices");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Valida DeltaMatroide");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Evalua Isomorfismo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator2);

        jMenuItem7.setText("Calcular Menores");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Clases de Delta-Equivalencia");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);
        jMenu2.add(jSeparator3);

        jMenuItem9.setText("Propiedades de DeltaMatroides");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem10.setText("Manual de usuario");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Acerca de ...");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String dms[] = jTextArea2.getText().split("\n");
            for (String dm : dms) {
                if (!dm.isEmpty()) {
                    String nombre = dm.split("=")[0];
                    ConstructorFamilias o = new ConstructorFamilias(dm.split("=")[1]);

                    DeltaMatroide add = new DeltaMatroide(o.getFamilia(), nombre, o.getConjuntoV());

                    folder.folder.add(new ElementoFolder(false, nombre, add, folder));
                    Main.cargaListaMatroides(listaMatroides);
                    jTextArea2.setText("");
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error, entrada ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void listaMatroidesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMatroidesMouseClicked
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) listaMatroides.getLastSelectedPathComponent();
        if (nodoSelec != null) {
            try {

                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();

                if (aux.isIsFolder()) {
                    folder = aux;
                    jLabel11.setText(folder.getNombre());

                }

            } catch (java.lang.ClassCastException ex) {

            }
        }
    }//GEN-LAST:event_listaMatroidesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String nombre = JOptionPane.showInputDialog("Escribe el nombre de la nueva Carpeta:");
       if(nombre!=null){
        folder.folder.add(new ElementoFolder(true, nombre, new LinkedList<ElementoFolder>(),folder));
        Main.cargaListaMatroides(listaMatroides); 
       }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Main.ventanaSelector= new SelectorMatroide(this, true, 5);
        Main.ventanaSelector.setVisible(true);
        ElementoFolder F= (ElementoFolder) Main.pila.pop();
        A.clear();
        for(ElementoFolder fi:F.folder) if(!fi.isIsFolder()) A.add(fi.getMatrode());
        cargaListaEnTabla(A,ModeloTablaA);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Main.ventanaSelector= new SelectorMatroide(this, true, 5);
        Main.ventanaSelector.setVisible(true);
        ElementoFolder F= (ElementoFolder) Main.pila.pop();
        B.clear();
        for(ElementoFolder fi:F.folder) if(!fi.isIsFolder()) B.add(fi.getMatrode());
        cargaListaEnTabla(B,ModeloTablaB);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int operacion=jComboBox1.getSelectedIndex();
        resultado=(new OperacionesListas()).getOperacion(operacion,A,B);
        cargaListaEnTabla(resultado,ModeloTablaR);
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(resultado.size()>0){
         Main.ventanaSelector= new SelectorMatroide(this, true, 5);
        Main.ventanaSelector.setVisible(true);
        ElementoFolder F= (ElementoFolder) Main.pila.pop();
        String[] botones={"Combinar contenidos","Crear una Subcarpeta"};
        int variable = JOptionPane.showOptionDialog (null, "¿Deseas guardar todos los delta-matroides en esta carpeta y \ncombinar su contenido o "
                + "crear una nueva subcarpeta?", "Combinar o subcarpeta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null/*icono*/, botones, botones[0]);
        switch(variable){
            case 0: 
                for(DeltaMatroide D:resultado){
                    ElementoFolder fi=new ElementoFolder(false,D.getNombreFam(),D, F);
                    F.folder.add(fi);
                }
            break;
            case 1:
                String nombre = JOptionPane.showInputDialog(
                        this,"Nombre de la nueva carpeta ", JOptionPane.INFORMATION_MESSAGE);
                ElementoFolder folder=new ElementoFolder(true, nombre, new LinkedList<ElementoFolder>(), F);
                for(DeltaMatroide D:resultado){
                    ElementoFolder fi=new ElementoFolder(false,D.getNombreFam(),D, folder);
                    folder.folder.add(fi);
                }
                F.folder.add(folder);
            break;
        }
        }else JOptionPane.showMessageDialog(this,"No hay elementos en la lista de resultado\npara guardar.");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void listaMatroides1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMatroides1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMatroides1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       LinkedList<ElementoFolder> copia=new LinkedList<>(),origen=new LinkedList<>();
        
        for (int i = 0; i < jTable4.getRowCount(); i++) {  
            if( (boolean)jTable4.getValueAt(i, 0))
                copia.add(folderAdmin.folder.get(i));
            else origen.add(folderAdmin.folder.get(i));
            
        }
        
        Main.ventanaSelector=new SelectorMatroide(this,true,5);
        Main.ventanaSelector.setVisible(true);
        ElementoFolder destino=(ElementoFolder) Main.pila.pop();
        
        if(destino!=null) {
            destino.folder.addAll(copia);
            folderAdmin.folder=origen;
            
        }
        cargaFolderEnTablaAdm(folderAdmin);
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void listaMatroides1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_listaMatroides1ValueChanged
        // TODO add your handling code here:
        
        
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) listaMatroides1.getLastSelectedPathComponent();
        if (nodoSelec != null) {
            try {

                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();

                if (aux.isIsFolder()) {
                   cargaFolderEnTablaAdm(aux);
                   cargaInformacion(aux);

                }

            } catch (java.lang.ClassCastException ex) {
                folderAdmin=Main.deltaMatroides;

            }
        }
    }//GEN-LAST:event_listaMatroides1ValueChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        LinkedList<ElementoFolder> fin=new LinkedList<>();
        for (int i = 0; i < jTable4.getRowCount(); i++) {
            
            if(! (boolean)jTable4.getValueAt(i, 0)){
                fin.add(folderAdmin.folder.get(i));
            }
            
        }
        folderAdmin.folder=fin;
        cargaFolderEnTablaAdm(folderAdmin);
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(folderAdmin.getNombre().compareTo("Delta-Matroides")!=0){
            folderAdmin.getNodoPadre().getFolder().remove(folderAdmin);
            
        }
        folderAdmin=new ElementoFolder(true, "", new LinkedList<ElementoFolder>(), Main.deltaMatroides);
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
        DefaultTableModel a=(DefaultTableModel) jTable4.getModel();
        a.setRowCount(0);
        jLabel5.setText("");
        jLabel14.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void listaMatroidesTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroidesTreeCollapsed
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=false;

            } catch (java.lang.ClassCastException ex) {
              
            }
        }
    }//GEN-LAST:event_listaMatroidesTreeCollapsed

    private void listaMatroidesTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroidesTreeExpanded
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=true;

            } catch (java.lang.ClassCastException ex) {
              
            }
        }
    }//GEN-LAST:event_listaMatroidesTreeExpanded

    private void listaMatroides1TreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroides1TreeCollapsed
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=false;

            } catch (java.lang.ClassCastException ex) {
              
            }
        }
    }//GEN-LAST:event_listaMatroides1TreeCollapsed

    private void listaMatroides1TreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listaMatroides1TreeExpanded
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSelec = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        
        if (nodoSelec != null) {
            try {
                ElementoFolder aux = (ElementoFolder) nodoSelec.getUserObject();
              aux.expandContra=true;

            } catch (java.lang.ClassCastException ex) {
              
            }
        }
    }//GEN-LAST:event_listaMatroides1TreeExpanded

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        LinkedList<ElementoFolder> copia=new LinkedList<>();
        
        for (int i = 0; i < jTable4.getRowCount(); i++) {  
            if( (boolean)jTable4.getValueAt(i, 0)){
                copia.add(folderAdmin.folder.get(i));
            }
        }
        
        Main.ventanaSelector=new SelectorMatroide(this,true,5);
        Main.ventanaSelector.setVisible(true);
        ElementoFolder destino=(ElementoFolder) Main.pila.pop();
        
        if(destino!=null) destino.folder.addAll(copia);
          
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Escribe el nombre de la nueva Carpeta:");
        if(nombre!=null){
            if(folderAdmin==null)   folderAdmin=Main.deltaMatroides;
           folderAdmin.folder.add(new ElementoFolder(true, nombre, new LinkedList<ElementoFolder>(),
                   folderAdmin));
        Main.cargaListaMatroides(listaMatroides);
        Main.cargaListaMatroides(listaMatroides1,0);
        
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        int tab=jTabbedPane1.getSelectedIndex();
        switch(tab){
            case 0: jLabel1.setText("Mueve, copia o elimina elementos y listas");
            break;
            case 1: jLabel1.setText("Crear una nueva lista de DeltaMatroides");
            break;
            case 2: jLabel1.setText("Compara dos listas de delta-matroides como conjuntos de listas");
            break;
            
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Main.menubarImportar(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Main.menubarExportar(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Main.ventanaGenera=new GeneradorDeltaMatroide();
        Main.ventanaGenera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Main.ventanaValidacion=new DeterminaDeltaMatroide()
                ;
        Main.ventanaValidacion.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Main.ventanaIsomorfismo=new Isomorfismo();
        Main.ventanaIsomorfismo.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Main.ventanaMenores=new Menores(null);
        Main.ventanaMenores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Main.ventanaEquivalencias=new GeneradorClaseEquivalencia();
        Main.ventanaEquivalencias.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Main.ventanaPropiedades=new DeltaMatroidePropiedades();
        Main.ventanaPropiedades.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Main.ventanaMenu=new Menu2();
        Main.ventanaMenu.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        ejecutaSalida();
    }//GEN-LAST:event_jButton15ActionPerformed
    private void ejecutaSalida(){
        switch(salida){
            case 0:
                Main.ventanaEquivalencias=new  GeneradorClaseEquivalencia();
                Main.ventanaEquivalencias.setVisible(true);
                this.setVisible(false);
            break;
            case 1:
                Main.ventanaIsomorfismo=new  Isomorfismo(1);
                Main.ventanaIsomorfismo.setVisible(true);
                this.setVisible(false);
            break;
        }
    }
    /**
     * @param args the command line arguments
     */
    @Override
    public void dispose() {

        if (JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas cerrar ProyectoDelta?", "¿Esta seguro?", JOptionPane.YES_NO_OPTION) == 0) {
            Main.guardarAreaDeTrabajo();
            super.dispose();
            System.exit(0);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree listaMatroides;
    private javax.swing.JTree listaMatroides1;
    // End of variables declaration//GEN-END:variables

    private boolean validaCampos() {
      return true;
    }

    private boolean validaCampos2() {
        return true;
    }

    

    private void cargaListaEnTabla(LinkedList<DeltaMatroide> A, DefaultTableModel ModeloTablaA) {
         ModeloTablaA.setRowCount(0);
        for (int i = 0; i < A.size(); i++) {
            DeltaMatroide get = A.get(i);
                get.setModeFactibles0();
                String renglon[] = {(i + 1) + "", get.getNombreFam(), get.getResultado()};
                ModeloTablaA.addRow(renglon);

            }

        }
        // listaDeIsomorfismo.setModel(modelo);

    private void cargaFolderEnTablaAdm(ElementoFolder aux) {
        
       TablaAdmi.setRowCount(0);
        folderAdmin=aux;
        for (int i = 0; i < folderAdmin.folder.size(); i++) {
            ElementoFolder get = folderAdmin.folder.get(i);
            String conte="",nombre;
            if(get.isIsFolder()) {
                conte="Carpeta";
                nombre=get.getNombre();
            }
            else {
                get.getMatrode().setModeFactibles0();
                conte=get.getMatrode().getResultado();
                nombre=get.getMatrode().getNombreFam();
                }
                Object renglon[] = {false,i + 1, nombre,conte };
                TablaAdmi.addRow(renglon);

            

        }
       
    }

    private void cargaInformacion(ElementoFolder aux) {
       jLabel5.setText(aux.getNombre());
       jLabel14.setText(aux.folder.size()+"");
    }
    
    
}
